---
title: "Comparison of BARK, BART and SVM"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Comparison of BARK, BART and SVM}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Installation

To get the latest version , install from github  (needs C++ compilation))

```{r, eval=FALSE}
devtools::install_github("merliseclyde/bark")
```

### Load Packages
```{r}
library(bark)
bart.available =  require(BART)
svm.available  =  require(e1071)
```


### Generate data

```{r}
set.seed(42)
n = 500
circle2 = as.data.frame(bark::sim_circle(n, dim = 2))

```

```{r, fig.width=4, fig.height=4 }
plot(x.1 ~ x.2, data=circle2, col=y+1)
```

```{r bark}
set.seed(42)
train = sample(1:n, size = floor(n/2), rep=FALSE)
circle2.bark = bark(as.matrix(circle2[train, 1:2]), circle2[train, 3], 
                              x.test = as.matrix(circle2[-train, 1:2]),
                    classification = TRUE,
                    type="se")
```

```{r}
#Classify
#
mean((circle2.bark$yhat.test.mean > 0) != circle2[-train, "y"])
```

## SVM

```{r svm}
if (svm.available) {
  circle2.svm = svm(y ~ x.1 + x.2, data=circle2[train,], type="C")
  pred.svm = predict(circle2.svm, circle2[-train,])
  mean(pred.svm != circle2[-train, "y"])
}

```


```{r bart}
if (bart.available) {
  circle.bart = pbart(x.train = circle2[train, 1:2], 
                            y.train =  circle2[train, "y"])
  pred.bart =   predict(circle.bart, circle2[-train, 1:2])
  mean((pred.bart$prob.test.mean > .5) != circle2[-train, "y"])
} 
```

Compare classification across methods.
```{r plots}

plot(x.1 ~ x.2, data=circle2[-train,], pch = y+15, 
     col=(1 + (circle2.bark$yhat.test.mean > 0)),
     main="bark")

if (bart.available) {
  plot(x.1 ~ x.2, data=circle2[-train,], pch = y+15, 
       col= ( 1 + (pred.bart$prob.test.mean > .5)), 
       main="BART")
}

if (svm.available) {
plot(x.1 ~ x.2, data=circle2[-train,], pch = y+15, 
     col= as.numeric(pred.svm), 
     main="svm")
}


```

